name: voice_nav_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  speech_to_text: ^7.0.0
  http: ^1.2.1

flutter:
  uses-material-design: true
